backend:
  name: github
  repo: nahmadic/airvat-gastby
media_folder: static/assets
public_folder: assets
collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: path, label: Path }
      - { name: bannerImg, label: 'Banner Image', widget: image, allow_multiple: false }
      - { name: body, label: Body, widget: markdown }